### ISSUE TITLE
bug: Tests are being installed as part of this package

### ISSUE THREAD

**Issue by msdinit** [googleapis/python-workflows#83] opened 2021-08-04 13:29 UTC
Previously I added a filter to setup.py to exclude `docs` and `tests` directories from being installed as a part of this library here https://github.com/googleapis/python-workflows/pull/63
but it looks like they are now being included in the source code again.
Moreover, it looks like they are now added even to the versions that did not have them previously, eg 1.0.0, so there does not seem to be a way to pin a release that does not supply you tests :)

As I am not sure how you package the release, I don't think I can contribute a PR with a fix, but please look into this.

To reproduce:
- install `google-cloud-workflows`
- observe `tests` package in your venv's site-packages

**Comment by grayside** [comment] 2022-03-10 19:52
Hi @busunkim96 , assigning this your way since you already have https://github.com/googleapis/python-memcache/issues/90

**Comment by averikitsch** [comment] 2022-05-19 16:48
The Dapple DPE team is using the label external to signify this is external from our commitments

**Comment by parthea** [comment] 2022-06-24 18:00
I'm not able to reproduce this issue with the latest version `1.6.3`. Please feel free to re-open this issue with more information.

```
root@410e4e65e9a4:/# pip install google-cloud-workflows
Collecting google-cloud-workflows
  Downloading google_cloud_workflows-1.6.3-py2.py3-none-any.whl (136 kB)
     |████████████████████████████████| 136 kB 5.2 MB/s            
Collecting google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5
  Downloading google_api_core-2.8.2-py3-none-any.whl (114 kB)
     |████████████████████████████████| 114 kB 42.2 MB/s            
Collecting proto-plus<2.0.0dev,>=1.15.0
  Downloading proto_plus-1.20.6-py3-none-any.whl (46 kB)
     |████████████████████████████████| 46 kB 3.9 MB/s             
Collecting protobuf<4.0.0dev,>=3.19.0
  Downloading protobuf-3.20.1-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 39.1 MB/s            
Collecting google-auth<3.0dev,>=1.25.0
  Downloading google_auth-2.8.0-py2.py3-none-any.whl (164 kB)
     |████████████████████████████████| 164 kB 40.5 MB/s            
Collecting requests<3.0.0dev,>=2.18.0
  Downloading requests-2.28.0-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 1.5 MB/s             
Collecting googleapis-common-protos<2.0dev,>=1.56.2
  Downloading googleapis_common_protos-1.56.3-py2.py3-none-any.whl (211 kB)
     |████████████████████████████████| 211 kB 37.5 MB/s            
Collecting grpcio-status<2.0dev,>=1.33.2
  Downloading grpcio_status-1.47.0-py3-none-any.whl (10.0 kB)
Collecting grpcio<2.0dev,>=1.33.2
  Downloading grpcio-1.47.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
     |████████████████████████████████| 4.5 MB 35.9 MB/s            
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
     |████████████████████████████████| 155 kB 36.1 MB/s            
Collecting cachetools<6.0,>=2.0.0
  Downloading cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.8-py3-none-any.whl (39 kB)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.10/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-workflows) (1.16.0)
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 8.2 MB/s             
Collecting certifi>=2017.4.17
  Downloading certifi-2022.6.15-py3-none-any.whl (160 kB)
     |████████████████████████████████| 160 kB 50.5 MB/s            
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 34.9 MB/s            
Collecting pyasn1<0.5.0,>=0.4.6
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
     |████████████████████████████████| 77 kB 6.5 MB/s             
Installing collected packages: pyasn1, urllib3, rsa, pyasn1-modules, protobuf, idna, charset-normalizer, certifi, cachetools, requests, grpcio, googleapis-common-protos, google-auth, grpcio-status, google-api-core, proto-plus, google-cloud-workflows
Successfully installed cachetools-5.2.0 certifi-2022.6.15 charset-normalizer-2.0.12 google-api-core-2.8.2 google-auth-2.8.0 google-cloud-workflows-1.6.3 googleapis-common-protos-1.56.3 grpcio-1.47.0 grpcio-status-1.47.0 idna-3.3 proto-plus-1.20.6 protobuf-3.20.1 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-2.28.0 rsa-4.8 urllib3-1.26.9
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.3.1; however, version 22.1.2 is available.
You should consider upgrading via the '/usr/local/bin/python3.10 -m pip install --upgrade pip' command.
root@410e4e65e9a4:/# which python3
/usr/local/bin/python3
root@410e4e65e9a4:/# pip show google-cloud-workflows
Name: google-cloud-workflows
Version: 1.6.3
Summary: 
Home-page: https://github.com/googleapis/python-workflows
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /usr/local/lib/python3.10/site-packages
Requires: google-api-core, proto-plus, protobuf
Required-by: 
root@410e4e65e9a4:/# ls  /usr/local/lib/python3.10/site-packages
CHANGELOG.md
LICENSE
README.md
README.txt
__pycache__
_distutils_hack
backports
backports.entry_points_selectable-1.1.0.dist-info
cachetools
cachetools-5.2.0.dist-info
certifi
certifi-2022.6.15.dist-info
charset_normalizer
charset_normalizer-2.0.12.dist-info
distlib
distlib-0.3.3.dist-info
distutils-precedence.pth
filelock
filelock-3.3.1.dist-info
google
google_api_core-2.8.2-py3.10-nspkg.pth
google_api_core-2.8.2.dist-info
google_auth-2.8.0-py3.10-nspkg.pth
google_auth-2.8.0.dist-info
google_cloud_workflows-1.6.3-py3.10-nspkg.pth
google_cloud_workflows-1.6.3.dist-info
googleapis_common_protos-1.56.3-py3.10-nspkg.pth
googleapis_common_protos-1.56.3.dist-info
grpc
grpc_status
grpcio-1.47.0.dist-info
grpcio_status-1.47.0.dist-info
idna
idna-3.3.dist-info
pip
pip-21.3.1.dist-info
pkg_resources
platformdirs
platformdirs-2.4.0.dist-info
proto
proto_plus-1.20.6.dist-info
protobuf-3.20.1-py3.10-nspkg.pth
protobuf-3.20.1.dist-info
pyasn1
pyasn1-0.4.8.dist-info
pyasn1_modules
pyasn1_modules-0.2.8.dist-info
requests
requests-2.28.0.dist-info
rsa
rsa-4.8.dist-info
setuptools
setuptools-58.3.0.dist-info
six-1.16.0.dist-info
six.py
urllib3
urllib3-1.26.9.dist-info
virtualenv
virtualenv-20.9.0.dist-info
wheel
wheel-0.37.0.dist-info
root@410e4e65e9a4:/# 
```

**Closed by parthea** 2022-06-24 18:00 UTC
Labels: type: bug, priority: p2, external, api: workflows
